//! Visual theme surface.
//!
//! Inherits the pleme-io workspace-wide theming primitives from
//! `irodzuki::ColorScheme` — the same base16 scheme `hibiki`, `kagi`,
//! `kekkai`, and (when wired) the rest of the GPU app family use. No
//! hand-coded hex values anywhere else in namimado; everything reads
//! through [`current_scheme`].
//!
//! Exposure surfaces:
//!
//! * `GET /theme`        → JSON ColorScheme (for agents + tooling)
//! * `GET /theme.css`    → CSS custom properties (the inspector SPA
//!                          loads this so its styling inherits the
//!                          system scheme automatically)
//! * `namimado::theme::current_scheme()` → Rust access (GPU window,
//!                          future chrome widgets, etc.)
//!
//! Later sessions swap in a shikumi-loaded scheme so the user can
//! point to their preferred base16 theme in config.

use irodzuki::ColorScheme;

/// The active color scheme. V1 returns the baked-in Nord-flavored
/// default; a later session adds shikumi config loading.
#[must_use]
pub fn current_scheme() -> ColorScheme {
    ColorScheme::default()
}

/// Emit a CSS stylesheet defining custom properties for every base16
/// slot + every SemanticColors role, plus a `[data-ast-source]` /
/// `[data-n-*]` family of provenance-highlight helpers.
///
/// The inspector SPA links this at runtime so a scheme swap is reflected
/// without rebuilding the binary.
#[must_use]
pub fn theme_css() -> String {
    let s = current_scheme();
    let mut out = String::new();
    out.push_str("/* generated by namimado::theme — inherits pleme-io irodzuki scheme */\n");
    out.push_str(":root {\n");
    // base16 slots
    write_var(&mut out, "--base00", s.base00.to_hex());
    write_var(&mut out, "--base01", s.base01.to_hex());
    write_var(&mut out, "--base02", s.base02.to_hex());
    write_var(&mut out, "--base03", s.base03.to_hex());
    write_var(&mut out, "--base04", s.base04.to_hex());
    write_var(&mut out, "--base05", s.base05.to_hex());
    write_var(&mut out, "--base06", s.base06.to_hex());
    write_var(&mut out, "--base07", s.base07.to_hex());
    write_var(&mut out, "--base08", s.base08.to_hex());
    write_var(&mut out, "--base09", s.base09.to_hex());
    write_var(&mut out, "--base0a", s.base0a.to_hex());
    write_var(&mut out, "--base0b", s.base0b.to_hex());
    write_var(&mut out, "--base0c", s.base0c.to_hex());
    write_var(&mut out, "--base0d", s.base0d.to_hex());
    write_var(&mut out, "--base0e", s.base0e.to_hex());
    write_var(&mut out, "--base0f", s.base0f.to_hex());
    // Semantic aliases (matching irodori::SemanticColors role map).
    // These are the names the inspector SPA uses; the palette can
    // change without the SPA needing to.
    write_var(&mut out, "--bg",         s.base00.to_hex());
    write_var(&mut out, "--bg-soft",    s.base01.to_hex());
    write_var(&mut out, "--selection",  s.base02.to_hex());
    write_var(&mut out, "--muted",      s.base03.to_hex());
    write_var(&mut out, "--fg-dim",     s.base04.to_hex());
    write_var(&mut out, "--fg",         s.base05.to_hex());
    write_var(&mut out, "--fg-bright",  s.base06.to_hex());
    write_var(&mut out, "--fg-max",     s.base07.to_hex());
    write_var(&mut out, "--error",      s.base08.to_hex());
    write_var(&mut out, "--warning",    s.base09.to_hex());
    write_var(&mut out, "--accent",     s.base0a.to_hex());
    write_var(&mut out, "--success",    s.base0b.to_hex());
    write_var(&mut out, "--info",       s.base0c.to_hex());
    write_var(&mut out, "--link",       s.base0d.to_hex());
    write_var(&mut out, "--special",    s.base0e.to_hex());
    write_var(&mut out, "--subtle",     s.base0f.to_hex());
    out.push_str("}\n");
    out
}

fn write_var(out: &mut String, key: &str, hex: String) {
    out.push_str("  ");
    out.push_str(key);
    out.push_str(": ");
    out.push_str(&hex);
    out.push_str(";\n");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scheme_is_non_empty() {
        let s = current_scheme();
        assert!(!s.name.is_empty());
    }

    #[test]
    fn theme_css_contains_every_base16_slot() {
        let css = theme_css();
        for slot in [
            "--base00", "--base01", "--base02", "--base03", "--base04",
            "--base05", "--base06", "--base07", "--base08", "--base09",
            "--base0a", "--base0b", "--base0c", "--base0d", "--base0e",
            "--base0f",
        ] {
            assert!(css.contains(slot), "theme.css missing {slot}");
        }
    }

    #[test]
    fn theme_css_contains_semantic_aliases() {
        let css = theme_css();
        for name in [
            "--bg", "--bg-soft", "--fg", "--fg-dim", "--fg-bright",
            "--accent", "--error", "--warning", "--success",
            "--selection", "--muted", "--link", "--info",
        ] {
            assert!(css.contains(name), "theme.css missing semantic alias {name}");
        }
    }

    #[test]
    fn theme_css_is_well_formed() {
        let css = theme_css();
        assert!(css.contains(":root {"));
        assert!(css.ends_with("}\n"));
    }

    #[test]
    fn theme_css_values_are_hex_and_unique_per_slot() {
        let css = theme_css();
        // Every base-slot value should be "#rrggbb" format.
        use std::collections::HashSet;
        let mut values = HashSet::new();
        for line in css.lines() {
            if let Some((_, rhs)) = line.split_once(":") {
                let val = rhs.trim().trim_end_matches(';').trim();
                if val.starts_with('#') && val.len() == 7 {
                    values.insert(val.to_ascii_lowercase());
                }
            }
        }
        // Nord has 16 distinct colors; we expect the scheme to use
        // them all (semantic aliases may duplicate base slots).
        assert!(values.len() >= 12, "expected diverse scheme; got {} colors", values.len());
    }

    #[test]
    fn default_scheme_is_deterministic() {
        assert_eq!(current_scheme().name, current_scheme().name);
        assert_eq!(current_scheme().base00.to_hex(), current_scheme().base00.to_hex());
    }
}
