//! Visual theme surface — shikumi-backed, hot-reloadable.
//!
//! Inherits the pleme-io workspace-wide theming primitives from
//! `irodzuki::ColorScheme` (base16) — same scheme `hibiki`, `kagi`,
//! `kekkai` consume. Resolution order:
//!
//! 1. `namimado.theme.scheme_file` — absolute path to a base16 YAML.
//! 2. `namimado.theme.scheme`       — named preset (`"nord"`, … ).
//! 3. Baked-in irodzuki default (Nord).
//!
//! **One edit, whole stack reflects.** Update
//! `~/.config/namimado/namimado.yaml`, call `POST /reload`, and every
//! surface (GPU window, inspector SPA via `/theme.css`, JSON at
//! `/theme`) re-derives from the fresh scheme in the same tick.
//!
//! Cached in a `RwLock` because readers outnumber writers by orders
//! of magnitude — every rendered frame pulls from it.

use irodzuki::ColorScheme;
use std::sync::RwLock;

use crate::config::NamimadoConfig;

static ACTIVE_SCHEME: RwLock<Option<ColorScheme>> = RwLock::new(None);

/// The active color scheme. Lazy-resolved on first call; `reload()`
/// clears the cache so the next call re-reads shikumi config.
#[must_use]
pub fn current_scheme() -> ColorScheme {
    if let Some(s) = ACTIVE_SCHEME.read().ok().and_then(|g| g.clone()) {
        return s;
    }
    let fresh = resolve_scheme();
    if let Ok(mut w) = ACTIVE_SCHEME.write() {
        *w = Some(fresh.clone());
    }
    fresh
}

/// Drop the cached scheme. Called from `POST /reload` + MCP `reload`.
/// Next `current_scheme()` re-reads config, re-loads any YAML file,
/// and re-derives.
pub fn reload() {
    if let Ok(mut w) = ACTIVE_SCHEME.write() {
        *w = None;
    }
}

fn resolve_scheme() -> ColorScheme {
    let cfg = NamimadoConfig::load();

    // 1. Explicit file path wins.
    if let Some(path) = &cfg.theme.scheme_file {
        match load_scheme_file(path) {
            Ok(s) => {
                tracing::info!(path = %path.display(), name = %s.name, "loaded scheme from file");
                return s;
            }
            Err(e) => {
                tracing::warn!(path = %path.display(), error = %e, "scheme file load failed; falling back");
            }
        }
    }

    // 2. Named preset.
    if let Some(name) = cfg.theme.scheme.as_deref() {
        match preset_by_name(name) {
            Some(s) => {
                tracing::info!(preset = %name, "loaded named preset");
                return s;
            }
            None => {
                tracing::warn!(preset = %name, "unknown scheme preset; falling back to default");
            }
        }
    }

    // 3. Default.
    ColorScheme::default()
}

fn load_scheme_file(path: &std::path::Path) -> Result<ColorScheme, String> {
    let raw = std::fs::read_to_string(path).map_err(|e| format!("read: {e}"))?;
    serde_yaml::from_str::<ColorScheme>(&raw).map_err(|e| format!("parse: {e}"))
}

fn preset_by_name(name: &str) -> Option<ColorScheme> {
    match name.trim().to_ascii_lowercase().as_str() {
        "nord" | "" => Some(ColorScheme::default()),
        // Future presets land here — the shape is `Some(ColorScheme)`.
        _ => None,
    }
}

/// Emit a CSS stylesheet defining custom properties for every base16
/// slot + every SemanticColors role. The inspector SPA links this.
#[must_use]
pub fn theme_css() -> String {
    let s = current_scheme();
    let mut out = String::new();
    out.push_str("/* generated by namimado::theme — inherits pleme-io irodzuki scheme */\n");
    out.push_str(&format!("/* active scheme: {:?} */\n", s.name));
    out.push_str(":root {\n");
    write_var(&mut out, "--base00", s.base00.to_hex());
    write_var(&mut out, "--base01", s.base01.to_hex());
    write_var(&mut out, "--base02", s.base02.to_hex());
    write_var(&mut out, "--base03", s.base03.to_hex());
    write_var(&mut out, "--base04", s.base04.to_hex());
    write_var(&mut out, "--base05", s.base05.to_hex());
    write_var(&mut out, "--base06", s.base06.to_hex());
    write_var(&mut out, "--base07", s.base07.to_hex());
    write_var(&mut out, "--base08", s.base08.to_hex());
    write_var(&mut out, "--base09", s.base09.to_hex());
    write_var(&mut out, "--base0a", s.base0a.to_hex());
    write_var(&mut out, "--base0b", s.base0b.to_hex());
    write_var(&mut out, "--base0c", s.base0c.to_hex());
    write_var(&mut out, "--base0d", s.base0d.to_hex());
    write_var(&mut out, "--base0e", s.base0e.to_hex());
    write_var(&mut out, "--base0f", s.base0f.to_hex());
    write_var(&mut out, "--bg",         s.base00.to_hex());
    write_var(&mut out, "--bg-soft",    s.base01.to_hex());
    write_var(&mut out, "--selection",  s.base02.to_hex());
    write_var(&mut out, "--muted",      s.base03.to_hex());
    write_var(&mut out, "--fg-dim",     s.base04.to_hex());
    write_var(&mut out, "--fg",         s.base05.to_hex());
    write_var(&mut out, "--fg-bright",  s.base06.to_hex());
    write_var(&mut out, "--fg-max",     s.base07.to_hex());
    write_var(&mut out, "--error",      s.base08.to_hex());
    write_var(&mut out, "--warning",    s.base09.to_hex());
    write_var(&mut out, "--accent",     s.base0a.to_hex());
    write_var(&mut out, "--success",    s.base0b.to_hex());
    write_var(&mut out, "--info",       s.base0c.to_hex());
    write_var(&mut out, "--link",       s.base0d.to_hex());
    write_var(&mut out, "--special",    s.base0e.to_hex());
    write_var(&mut out, "--subtle",     s.base0f.to_hex());
    out.push_str("}\n");
    out
}

fn write_var(out: &mut String, key: &str, hex: String) {
    out.push_str("  ");
    out.push_str(key);
    out.push_str(": ");
    out.push_str(&hex);
    out.push_str(";\n");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scheme_is_non_empty() {
        let s = current_scheme();
        assert!(!s.name.is_empty());
    }

    #[test]
    fn theme_css_contains_every_base16_slot() {
        let css = theme_css();
        for slot in [
            "--base00", "--base01", "--base02", "--base03", "--base04",
            "--base05", "--base06", "--base07", "--base08", "--base09",
            "--base0a", "--base0b", "--base0c", "--base0d", "--base0e",
            "--base0f",
        ] {
            assert!(css.contains(slot), "theme.css missing {slot}");
        }
    }

    #[test]
    fn theme_css_contains_semantic_aliases() {
        let css = theme_css();
        for name in [
            "--bg", "--bg-soft", "--fg", "--fg-dim", "--fg-bright",
            "--accent", "--error", "--warning", "--success",
            "--selection", "--muted", "--link", "--info",
        ] {
            assert!(css.contains(name), "theme.css missing semantic alias {name}");
        }
    }

    #[test]
    fn theme_css_is_well_formed() {
        let css = theme_css();
        assert!(css.contains(":root {"));
        assert!(css.ends_with("}\n"));
    }

    #[test]
    fn theme_css_advertises_active_scheme_name() {
        let css = theme_css();
        let name = current_scheme().name;
        assert!(css.contains(&name), "scheme name {name:?} missing from CSS header");
    }

    #[test]
    fn reload_clears_the_cache() {
        let _ = current_scheme();
        reload();
        // Next call should re-populate — just prove it doesn't panic
        // + returns a valid scheme.
        let s = current_scheme();
        assert!(!s.name.is_empty());
    }

    #[test]
    fn preset_by_name_resolves_nord_and_rejects_unknown() {
        assert!(preset_by_name("nord").is_some());
        assert!(preset_by_name("Nord").is_some());
        assert!(preset_by_name("NORD").is_some());
        assert!(preset_by_name("").is_some()); // empty falls to default
        assert!(preset_by_name("solarized-dark").is_none()); // not yet shipped
    }

    #[test]
    fn load_scheme_file_roundtrips_yaml() {
        // Write an irodzuki ColorScheme out as YAML, read it back.
        let tmp = std::env::temp_dir().join(format!(
            "namimado-theme-test-{}.yaml",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        let scheme = ColorScheme::default();
        let yaml = serde_yaml::to_string(&scheme).unwrap();
        std::fs::write(&tmp, yaml).unwrap();

        let loaded = load_scheme_file(&tmp).expect("load");
        assert_eq!(loaded.name, scheme.name);
        assert_eq!(loaded.base00.to_hex(), scheme.base00.to_hex());

        std::fs::remove_file(&tmp).ok();
    }

    #[test]
    fn load_scheme_file_rejects_missing_path() {
        let path = std::path::Path::new("/nonexistent/namimado-theme.yaml");
        let err = load_scheme_file(path).unwrap_err();
        assert!(err.contains("read"));
    }
}
